- # Module- when a .py containing too much functions or global  variables called mudule
- # Package- when collection of Module used called package[x.py ,y.py,z.py ] ex- random , os , pandas , math
- # Library- collection of diff modules along eith packages called library  . ex - numpy , pandas , matplotlib , seaborn  

- Numpy- Numeric values only used, used to create 1d,2d,multi dimension array which stores numerical values.

In [2]:
import numpy as np
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
arr2=np.array([10,20,30])
arr1=np.array([[1,2,3],[4,5,6]])
arr3=np.array([[[1,2,3],[3,4,5],[6,7,8]]])

In [4]:
print(arr1)

[[1 2 3]
 [4 5 6]]


In [5]:
print(arr3)

[[[1 2 3]
  [3 4 5]
  [6 7 8]]]


In [6]:
np.array([1,2,3],dtype="complex")

array([1.+0.j, 2.+0.j, 3.+0.j])

In [7]:
# addition of array
print(arr1+arr2)

[[11 22 33]
 [14 25 36]]


- for list


In [8]:
list=[1,2,3]
list1=[10,20,30]  # when we use + in list it concatecate the list but 
                   #if we use + in array is add the values of array
print(list+list1)

[1, 2, 3, 10, 20, 30]


In [9]:
list_ans=[]
for i,j in zip(list,list1):
  list_ans.append(i+j)
print(list_ans)  

[11, 22, 33]


- # Major difference b/w numpy array and list.
- numpy array have fixed size of array creation but if it is not in the case when we tslk about list.
- the elements in the numpy array are all required to similar data type.
- numpy takes less time to perform arithmetic activities whereas list take more time.
- numpy takes less space.


In [10]:
# checking dimension of array
arr2.ndim 

1

In [11]:
arr3.ndim

3

In [12]:
arr3.size  # size of array


9

In [13]:
# checking shape of the array
arr2.shape

(3,)

In [14]:
arr3.shape

(1, 3, 3)

In [15]:
arr1.shape

(2, 3)

- # Attribute of array


In [16]:
# arrange
a1=np.arange(10)
print(a1)      # arrange method create only 1D array within given range.

[0 1 2 3 4 5 6 7 8 9]


In [17]:
a2=np.arange(20,dtype="float")
print(a2)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]


In [18]:
# convertion 1D to 2D array

a2=a2.reshape(4,5)

In [19]:
print(a2)

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]]


In [20]:
a2=a2.astype(np.int64)


In [21]:
a2*4


array([[ 0,  4,  8, 12, 16],
       [20, 24, 28, 32, 36],
       [40, 44, 48, 52, 56],
       [60, 64, 68, 72, 76]], dtype=int64)

In [22]:
for i in a2:
    print(i)   # row vise value.

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [23]:
for i in np.nditer(a2):
    print(i)            # it takes all the values one by one.

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


- # Data Manipulation using numpy
- Different ways of creating numpy arrays

In [26]:
import numpy as np
var_1=np.array([1,2,3,4])
var_1

array([1, 2, 3, 4])

In [29]:
# arrays of zeros
z=np.zeros((4,3),dtype="int")
z


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
y=np.ones((2,2),dtype="int")  # array of ones
y

array([[1, 1],
       [1, 1]])

In [33]:
# random array
ar=np.random.rand(3,4)
ar

array([[0.41247614, 0.44143074, 0.81493383, 0.28473258],
       [0.53373728, 0.37033472, 0.81985429, 0.48233382],
       [0.15801638, 0.86717099, 0.60098638, 0.1490546 ]])

In [36]:
#if you want to fix the randomness
np.random.seed(4)
arr=np.random.rand(4,4)
arr

array([[0.96702984, 0.54723225, 0.97268436, 0.71481599],
       [0.69772882, 0.2160895 , 0.97627445, 0.00623026],
       [0.25298236, 0.43479153, 0.77938292, 0.19768507],
       [0.86299324, 0.98340068, 0.16384224, 0.59733394]])

In [37]:
# for negation
ar1=np.random.randn(4,4)
ar1

array([[ 0.61866969, -0.08798693,  0.4250724 ,  0.33225315],
       [-1.15681626,  0.35099715, -0.60688728,  1.54697933],
       [ 0.72334161,  0.04613557, -0.98299165,  0.05443274],
       [ 0.15989294, -1.20894816,  2.22336022,  0.39429521]])

In [39]:
# in random method we can't change data type of array
p=np.random.randint(low=50,high=100,size=(4,4))
p


array([[93, 58, 87, 58],
       [89, 82, 80, 54],
       [61, 58, 86, 81],
       [90, 67, 64, 59]])

- Slicing and Indexing

In [40]:
p[1,1]

82

In [43]:
p[0:2,0:3]

array([[93, 58, 87],
       [89, 82, 80]])

# Manipulation of array

In [44]:
# creating identity metrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
b=np.arange(1,13).reshape(4,3)
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
b=b.ravel()  # flattening
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [50]:
c=np.arange(1,13).reshape(3,4)
#c.transpose()
c.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

# Stacking and Splitting of matrix


In [51]:
mat1=np.arange(12).reshape(4,3)
mat2=np.arange(12,24).reshape(4,3)

In [52]:
mat1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [53]:
mat2

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [59]:
v=np.vstack((mat1,mat2))
v

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [60]:
h=np.hstack((mat1,mat2))
h

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17],
       [ 6,  7,  8, 18, 19, 20],
       [ 9, 10, 11, 21, 22, 23]])

In [61]:
np.hsplit(h,2)

[array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]])]

In [62]:
np.vsplit(v,4)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]]),
 array([[18, 19, 20],
        [21, 22, 23]])]