- # Module- when a .py containing too much functions or global  variables called mudule
- # Package- when collection of Module used called package[x.py ,y.py,z.py ] ex- random , os , pandas , math
- # Library- collection of diff modules along eith packages called library  . ex - numpy , pandas , matplotlib , seaborn  

- Numpy- Numeric values only used, used to create 1d,2d,multi dimension array which stores numerical values.

In [1]:
import numpy as np
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [6]:
arr2=np.array([10,20,30])
arr1=np.array([[1,2,3],[4,5,6]])
arr3=np.array([[[1,2,3],[3,4,5],[6,7,8]]])

In [7]:
print(arr1)

[[1 2 3]
 [4 5 6]]


In [8]:
print(arr3)

[[[1 2 3]
  [3 4 5]
  [6 7 8]]]


In [9]:
np.array([1,2,3],dtype="complex")

array([1.+0.j, 2.+0.j, 3.+0.j])

In [10]:
# addition of array
print(arr1+arr2)

[[11 22 33]
 [14 25 36]]


- for list


In [ ]:
list=[1,2,3]
list1=[10,20,30]  # when we use + in list it concatecate the list but 
                   #if we use + in array is add the values of array
print(list+list1)

[1, 2, 3, 10, 20, 30]


In [13]:
list_ans=[]
for i,j in zip(list,list1):
  list_ans.append(i+j)
print(list_ans)  

[11, 22, 33]


- # Major difference b/w numpy array and list.
- numpy array have fixed size of array creation but if it is not in the case when we tslk about list.
- the elements in the numpy array are all required to similar data type.
- numpy takes less time to perform arithmetic activities whereas list take more time.
- numpy takes less space.


In [15]:
# checking dimension of array
arr2.ndim 

1

In [16]:
arr3.ndim

3

In [ ]:
arr3.size  # size of array


9

In [18]:
# checking shape of the array
arr2.shape

(3,)

In [19]:
arr3.shape

(1, 3, 3)

In [20]:
arr1.shape

(2, 3)

- # Attribute of array


In [ ]:
# arrange
a1=np.arange(10)
print(a1)      # arrange method create only 1D array within given range.

[0 1 2 3 4 5 6 7 8 9]


In [23]:
a2=np.arange(20,dtype="float")
print(a2)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]


In [24]:
# convertion 1D to 2D array

a2=a2.reshape(4,5)

In [25]:
print(a2)

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]]


In [ ]:
a2=a2.astype(np.int64)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]], dtype=int64)

In [27]:
a2*4


array([[ 0.,  4.,  8., 12., 16.],
       [20., 24., 28., 32., 36.],
       [40., 44., 48., 52., 56.],
       [60., 64., 68., 72., 76.]])

In [ ]:
for i in a2:
    print(i)   # row vise value.

[0. 1. 2. 3. 4.]
[5. 6. 7. 8. 9.]
[10. 11. 12. 13. 14.]
[15. 16. 17. 18. 19.]


In [ ]:
for i in np.nditer(a2):
    print(i)            # it takes all the values one by one.

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
11.0
12.0
13.0
14.0
15.0
16.0
17.0
18.0
19.0
